name: Build and Deploy .NET API (QA → PROD using azure/login)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

# 🔹 1. BUILD
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./publish


# 🔹 2. DEPLOY TO QA (AUTO)
  deploy-qa:
    runs-on: ubuntu-latest
    needs: build
    environment: qa

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      # 🔐 Azure Login (OIDC)
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F923CE1D661F4B5C8CB6856292E7D75C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_99D4B8B10C7F456183101AFA9AA65576 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_322BF678FCA44E53959B7C5CF341F1C2 }}

      - name: Deploy to QA Slot
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'myfirstdotnetcoreapi'
          slot-name: 'qa'   # 🔥 QA slot
          package: .


# 🔹 3. DEPLOY TO PRODUCTION (MANUAL APPROVAL)
  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-qa
    environment: production   # 🔥 requires approval

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      # 🔐 Azure Login (OIDC)
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F923CE1D661F4B5C8CB6856292E7D75C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_99D4B8B10C7F456183101AFA9AA65576 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_322BF678FCA44E53959B7C5CF341F1C2 }}

      - name: Deploy to Production
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'myfirstdotnetcoreapi'
          package: .   # 🔥 no slot-name for production